/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class photostudio_image_ImageData */

#ifndef _Included_photostudio_image_ImageData
#define _Included_photostudio_image_ImageData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     photostudio_image_ImageData
 * Method:    createJni
 * Signature: (Ljava/lang/String;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_photostudio_image_ImageData_createJni
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     photostudio_image_ImageData
 * Method:    destroyJni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_photostudio_image_ImageData_destroyJni
  (JNIEnv *, jobject);

/*
 * Class:     photostudio_image_ImageData
 * Method:    isCreatedJni
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_photostudio_image_ImageData_isCreatedJni
  (JNIEnv *, jobject);

/*
 * Class:     photostudio_image_ImageData
 * Method:    setImageNameJni
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_photostudio_image_ImageData_setImageNameJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     photostudio_image_ImageData
 * Method:    getImageNameJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_photostudio_image_ImageData_getImageNameJni
  (JNIEnv *, jobject);

/*
 * Class:     photostudio_image_ImageData
 * Method:    getImageInfoJni
 * Signature: ()Lphotostudio/image/ImageInfo;
 */
JNIEXPORT jobject JNICALL Java_photostudio_image_ImageData_getImageInfoJni
  (JNIEnv *, jobject);

/*
 * Class:     photostudio_image_ImageData
 * Method:    getPixelJni
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_photostudio_image_ImageData_getPixelJni
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     photostudio_image_ImageData
 * Method:    setPixelJni
 * Signature: (II[I)Z
 */
JNIEXPORT jboolean JNICALL Java_photostudio_image_ImageData_setPixelJni
  (JNIEnv *, jobject, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
