/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class photostudio_image_ImageWriter */

#ifndef _Included_photostudio_image_ImageWriter
#define _Included_photostudio_image_ImageWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     photostudio_image_ImageWriter
 * Method:    write
 * Signature: (Ljava/lang/String;Lphotostudio/image/IImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_photostudio_image_ImageWriter_write
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
