/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class photostudio_image_ImageLibrary */

#ifndef _Included_photostudio_image_ImageLibrary
#define _Included_photostudio_image_ImageLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     photostudio_image_ImageLibrary
 * Method:    getDataBufferJni
 * Signature: ([BLphotostudio/image/IImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_photostudio_image_ImageLibrary_getDataBufferJni
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
