/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class photostudio_image_ImageReader */

#ifndef _Included_photostudio_image_ImageReader
#define _Included_photostudio_image_ImageReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     photostudio_image_ImageReader
 * Method:    read
 * Signature: (Ljava/lang/String;Lphotostudio/image/IImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_photostudio_image_ImageReader_read
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
