/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class photostudio_image_ImageFactory */

#ifndef _Included_photostudio_image_ImageFactory
#define _Included_photostudio_image_ImageFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     photostudio_image_ImageFactory
 * Method:    createInstance
 * Signature: ()Lphotostudio/image/IImageData;
 */
JNIEXPORT jobject JNICALL Java_photostudio_image_ImageFactory_createInstance
  (JNIEnv *, jclass);

/*
 * Class:     photostudio_image_ImageFactory
 * Method:    duplicateInstance
 * Signature: (Lphotostudio/image/IImageData;)Lphotostudio/image/IImageData;
 */
JNIEXPORT jobject JNICALL Java_photostudio_image_ImageFactory_duplicateInstance
  (JNIEnv *, jclass, jobject);

/*
 * Class:     photostudio_image_ImageFactory
 * Method:    destroyInstance
 * Signature: (Lphotostudio/image/IImageData;)V
 */
JNIEXPORT void JNICALL Java_photostudio_image_ImageFactory_destroyInstance
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
